/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppChangesIndexRouteImport } from './routes/app.changes.index'
import { Route as AppChangesChangeIdRouteImport } from './routes/app.changes.$changeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppChangesIndexRoute = AppChangesIndexRouteImport.update({
  id: '/changes/',
  path: '/changes/',
  getParentRoute: () => AppRoute,
} as any)
const AppChangesChangeIdRoute = AppChangesChangeIdRouteImport.update({
  id: '/changes/$changeId',
  path: '/changes/$changeId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/app/': typeof AppIndexRoute
  '/app/changes/$changeId': typeof AppChangesChangeIdRoute
  '/app/changes/': typeof AppChangesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/app': typeof AppIndexRoute
  '/app/changes/$changeId': typeof AppChangesChangeIdRoute
  '/app/changes': typeof AppChangesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/how-it-works': typeof HowItWorksRoute
  '/app/': typeof AppIndexRoute
  '/app/changes/$changeId': typeof AppChangesChangeIdRoute
  '/app/changes/': typeof AppChangesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/how-it-works'
    | '/app/'
    | '/app/changes/$changeId'
    | '/app/changes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/how-it-works'
    | '/app'
    | '/app/changes/$changeId'
    | '/app/changes'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/how-it-works'
    | '/app/'
    | '/app/changes/$changeId'
    | '/app/changes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
  HowItWorksRoute: typeof HowItWorksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/changes/': {
      id: '/app/changes/'
      path: '/changes'
      fullPath: '/app/changes/'
      preLoaderRoute: typeof AppChangesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/changes/$changeId': {
      id: '/app/changes/$changeId'
      path: '/changes/$changeId'
      fullPath: '/app/changes/$changeId'
      preLoaderRoute: typeof AppChangesChangeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppChangesChangeIdRoute: typeof AppChangesChangeIdRoute
  AppChangesIndexRoute: typeof AppChangesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppChangesChangeIdRoute: AppChangesChangeIdRoute,
  AppChangesIndexRoute: AppChangesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
  HowItWorksRoute: HowItWorksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
